name: Platform
version: 0.0.1
port: 3000
data:
  ini: data/init
  unit: data/unit
  download: data/download
  backup: data/backup
log:
  level: debug
  path: logs
  name: platform
  console: true
axios:
  timeout: 5000
  maxRedirects: 5
database:
  type: postgresql
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456
  database: at_platform
crypto:
  pbk: '222'
  saltKey: ssss
jwt:
  key: qzBra0aKNgqxL6mmCtH7IxJXd9I/diT7+OEgh9eziYk=
  expired: 3600
